# Version of the configuration file
version: 5.1.0
# Icarus theme variant, can be "default" or "cyberpunk"
variant: default
# Path or URL to the website's logo
logo: https://lzhms.oss-cn-hangzhou.aliyuncs.com/images/blog/profile/logo_light.png
logo_dark: https://lzhms.oss-cn-hangzhou.aliyuncs.com/images/blog/profile/logo_dark.png
# Page metadata configurations
head:
    # URL or path to the website's icon
    favicon: https://lzhms.oss-cn-hangzhou.aliyuncs.com/images/blog/profile/logo_light.png
    # Web application manifests configuration
    # https://developer.mozilla.org/en-US/docs/Web/Manifest
    manifest:
        # Name of the web application (default to the site title)
        name: Zhihao Li - Zhihao Li's Blog
        # The displayed name of the web application
        # when there is not enough space to display full name
        short_name: Zhihao Li
        # The start URL of the web application
        start_url: https://github.com/LZHMS/LZHMS.github.io
        # The default theme color for the application
        theme_color: "#3273dc"
        # A placeholder background color for the application page to display
        # before its stylesheet is loaded
        background_color: "#3273dc"
        # The preferred display mode for the website
        display: standalone
        # Image files that can serve as application icons for different contexts
        icons:
            -
                # The path to the image file
                src: ''
                # A string containing space-separated image dimensions
                sizes: ''
                # A hint as to the media type of the image
                type: 
    # Open Graph metadata
    # https://hexo.io/docs/helpers.html#open-graph
    open_graph:
        # Page title (og:title) (optional)
        # You should leave this blank for most of the time
        title:
        # Page type (og:type) (optional)
        # You should leave this blank for most of the time
        type: blog
        # Page URL (og:url) (optional)
        # You should leave this blank for most of the time
        url: 
        # Page cover (og:image) (optional)
        # You should leave this blank for most of the time
        image: 
        # Site name (og:site_name) (optional)
        # You should leave this blank for most of the time
        site_name:
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author:
        # Page description (og:description) (optional)
        # You should leave this blank for most of the time
        description: 
        # Twitter card type (twitter:card)
        twitter_card: 
        # Twitter ID (twitter:creator)
        twitter_id: 
        # Twitter Site (twitter:site)
        twitter_site: 
        # Google+ profile link (deprecated)
        google_plus: 
        # Facebook admin ID
        fb_admins: 
        # Facebook App ID
        fb_app_id:
    # Structured data of the page
    # https://developers.google.com/search/docs/guides/intro-structured-data
    structured_data:
        # Page title (optional)
        # You should leave this blank for most of the time
        title: 
        # Page description (optional)
        # You should leave this blank for most of the time
        description: 
        # Page URL (optional)
        # You should leave this blank for most of the time
        url: 
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author: 
        # Page publisher (optional)
        # You should leave this blank for most of the time
        publisher: 
        # Page publisher logo (optional)
        # You should leave this blank for most of the time
        publisher_logo: 
        # Page images (optional)
        # You should leave this blank for most of the time
        image: 
    # Additional HTML meta tags in an array
    meta:
        # Meta tag specified in <attribute>=<value> style
        # E.g., name=theme-color;content=#123456 => <meta name="theme-color" content="#123456">
        - ''
    # URL or path to the website's RSS atom.xml
    rss: 
# Page top navigation bar configurations
navbar:
    # Navigation menu items
    menu:
        ZHIHAO LI'S LOG BOOK: /
        BLOG: /blog
        KNOWLEDGE: /knowledge
        PUBLICATIONS: /publications
        PROJECTS: /projects
        ESSAY: /essay
        READINGS: /readings
        COLLABORATION: /collaboration
        ARCHIVES: /archives
        CATEGORIES: /categories
        TAGS: /tags
    # Links to be shown on the right of the navigation bar
    links:
        GitHub:
            icon: iconfont icon-github
            url: https://github.com/LZHMS
        Gitee:
            icon: iconfont icon-gitee1
            url: https://gitee.com/LZHMS
# Page footer configurations
footer:
    # Copyright text
    copyright: ' '
    # Links to be shown on the right of the footer section
    links:
        HuggingFace:
            icon: iconfont icon-huggingface
            url: https://huggingface.co/LZHMS
        ZhiHu:
            icon: iconfont icon-zhihu
            url: https://www.zhihu.com/people/zhao.li
        CSDN:
            icon: iconfont icon-csdn
            url: https://blog.csdn.net/weixin_63554791
# Article related configurations
article:
    # Code highlight settings
    highlight:
        # Code highlight themes
        # https://github.com/highlightjs/highlight.js/tree/master/src/styles
        theme: atom-one-light
        # Show copy code button
        clipboard: true
        # Default folding status of the code blocks. Can be "", "folded", "unfolded"
        fold: "unfolded"
    # Whether to show estimated article reading time
    readtime: true
    # Whether to show updated time. For "auto", shows article update time only when page.updated is set and it is different from page.date
    update_time: true
    # Article licensing block
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
# Search plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search/
search:
    type: insight
    # Whether to include pages in the search results
    index_pages: true
# Comment plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment/
comment:
    type: twikoo
    env_id: https://twikoo-netlify-comment.netlify.app/.netlify/functions/twikoo
    region: ap-guangzhou     # 可选填
    lang: en              # 可选填
    
    # type: giscus
    # repo: LZHMS/Discussion                   # 必填项
    # repoId: R_kgDOMsC_6Q             # 必填项
    # category: Announcements          # 可选填，默认为 Announcements
    # categoryId: DIC_kwDOMsC_6c4CiKeP # 必填项
    # mapping: pathname                # 可选填，默认为 pathname
    # strict: false                    # 可选填
    # reactionsEnabled: true          # 可选填
    # emitMetadata: false              # 可选填
    # inputPosition: top               # 可选填，默认为 top
    # theme: noborder_light            # 可选填
    # lang: en                         # 可选填，默认为 en
    # lazy: true                       # 可选填，默认为 false

# Share plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share/
share:
    type: sharethis
    # URL to the ShareThis share plugin script
    install_url: https://platform-api.sharethis.com/js/sharethis.js#property=6713c7a4f9d5250012f5d817&product=inline-reaction-buttons&source=platform

# Sidebar configurations.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
    # Left sidebar configurations
    left:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: true
    # Right sidebar configurations
    right:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: true
# Sidebar widget configurations
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    # Profile widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: profile
        # Author name
        author: Zhihao Li
        # Author title
        author_title: |
            Computer Science
            Graphics & 3D Vision
            
        # Author's current location
        location: Xidian University, Xi'an, China
        # Author's hometown
        # URL or path to the avatar image
        avatar: https://lzhms.oss-cn-hangzhou.aliyuncs.com/images/blog/profile/avatar.png
        # Whether show the rounded avatar image
        avatar_rounded: true
        # Email address for the Gravatar
        gravatar:
        # URL or path for the follow button
        follow_link: https://github.com/LZHMS
        # Links to be shown on the bottom of the profile widget
        social_links:
            Bilibili:
                icon: iconfont icon-bilibili
                url: https://space.bilibili.com/2079836440
            Cnblog:
                icon: iconfont icon-cnblogs
                url: https://www.cnblogs.com/LZHMS/
            QQ:
                icon: iconfont icon-QQ1
                url: https://jsd.cdn.zzko.cn/gh/LZHMS/picx-images-hosting@master/Profile/1730463517285_temp_qrcode_share_9993.64dv175zqu.webp
            WeChat:
                icon: iconfont icon-wechat-
                url: https://jsd.cdn.zzko.cn/gh/LZHMS/picx-images-hosting@master/Profile/0add852711e38990022788ba88dd062.3nrmm9y3ql.webp
            Email:
                icon: iconfont icon-email2
                url: mailto:zhihaoli@stu.xidian.edu.cn
    # Table of contents widget configurations
    -
        # WhereEmail should the widget be placed, left sidebar or right sidebar
        position: left
        type: toc
        # Whether to show the index of each heading
        index: true
        # Whether to collapse sub-headings when they are out-of-view
        collapsed: true
        # Maximum level of headings to show (1-6)
        depth: 6
    # Categories widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: categories
    # Recent posts widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: recent_posts
    # Archives widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: archives
    # Tags widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: tags
        # How to order tags. For example 'name' to order by name in ascending order, and '-length' to order by number of posts in each tags in descending order
        order_by: name
        # Amount of tags to show. Will show all if not set.
        amount: 
        # Whether to show tags count, i.e. number of posts in the tag.
        show_count: true

    # Follow.it email subscription widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: followit
        # Hint text under the email input
        description: 
        # Subscription form action URL
        action_url: 'https://api.follow.it/subscription-form/MUlhbUpwUW5ra0pneVRkNWlJSWwxS2VOeDVtWEtzUzRUcHYwRmR3Uld4Ym1YY2VkQktrZjFEYTg3ZWhSN2ozQ3ZVdHpZTXAyTjFNMWpqa2NOMFY3Nm9aeXRGdkFNSjAzWWM0Vk1LcUMvUG5jdm9sRXg5eXBlbVQvQ1loVmgxNHl8Wm1vREw3Sk5PaXZMVmZJc3pTeVJTbTFneW8wRmlMdUFqN2lvbzdYTHc3RT0=/21'
        # Feed claiming verification code
        verification_code: '9wSCtL5bT19tB18CXfYP'
# Plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/
plugins:
    # Enable page startup animations
    animejs: true
    # Show the "back to top" button
    back_to_top: true
    # BuSuanZi site/page view counter
    # https://busuanzi.ibruce.info
    busuanzi: true
    # Enable the lightGallery and Justified Gallery plugins
    gallery: true
    # Google Analytics plugin settings
    # https://analytics.google.com
    # Enable the KaTeX math typesetting support
    # https://katex.org/
    katex: true
    # Enable the MathJax math typesetting support
    # https://www.mathjax.org/
    mathjax: true
    # Enable the Outdated Browser plugin
    # http://outdatedbrowser.com/
    outdated_browser: false
    # Show a progress bar at top of the page on page loading
    progressbar: true
# CDN provider settings
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # Name or URL template of the JavaScript and/or stylesheet CDN provider 
    cdn: loli
    # Name or URL template of the webfont CDN provider
    fontcdn: loli
    # Name or URL of the ome icon font CDN provider
    iconcdn: loli

# DPlayer
dplayer:
  enable: true
  useCDN: true